export const IntroData = [
  {
    id: 1,
    image: "/images/tincongnghe/1.png",
    tags: "Tin mới",
    date: "26 tháng 03 năm 2022",
    title: "TRÍ TUỆ NHÂN TẠO",
    text: "Mark Gurman của Bloomberg báo cáo rằng Apple có thể sẽ triển khai dịch vụ sử dụng iPad và iPhone mới. Về bản chất, người dùng sẽ phải trả một khoản phí cố định mỗi tháng và nhận được một thiết bị mà họ lựa chọn với các bản nâng cấp miễn phí khi các mẫu điện thoại mới được công bố.",
  },
  {
    id: 2,
    image: "/images/tincongnghe/2.png",
    tags: "Tin mới",
    date: "22 tháng 03 năm 2022",
    title: "GIẢI PHÁP CÔNG NGHỆ PHẦN MỀM",
    text: "Mới đây, chuyên gia rò rỉ nổi tiếng Digital Chat Station đã chia sẻ một báo cáo thú vị về cảm biến Sony sắp ra mắt đang được bàn giao cho các nhà sản xuất để thử nghiệm. Một số suy đoán đó là cảm biến Exmor IMX800 dành cho Xiaomi 12 Ultra.",
  },
  {
    id: 3,
    image: "/images/tincongnghe/3.png",
    tags: "Sản phẩm mới",
    date: "26 tháng 03 năm 2022",
    title: "DỊCH VỤ CUNG CẤP SẢN PHẨM CÔNG NGHỆ",
    text: "Vài ngày trước, có tin đồn Samsung sẽ ra mắt thêm một mẫu điện thoại gập khác bên cạnh Z Flip 4 và Z Fold 4 trong năm nay. Rò rỉ mới đây cho biết đó có thể là điện thoại màn hình cuộn đầu tiên được Samsung giới thiệu đến người dùng toàn cầu. ",
  },
  {
    id: 4,
    image: "/images/tincongnghe/4.png",
    tags: "Sản phẩm mới",
    date: "26 tháng 03 năm 2022",
    title: "NGHIÊN CỨU PHÁT TRIỂN SẢN PHẨM DOANH NGHIỆP",
    text: "Redmi Book Pro 15 2022 đi kèm với thân máy bằng hợp kim nhôm mà công ty cho biết có thể chịu được mài mòn. Nó có cảm biến vân tay tích hợp vào nút nguồn, có bàn di chuột rộng và có webcam 720p.",
  },
  {
    id: 5,
    image: "/images/tincongnghe/5.png",
    tags: "Tin mới",
    date: "26 tháng 03 năm 2022",
    title: "TỤ ĐỘNG HÓA DÂY CHUYỀN SẢN XUẤT",
    text: "Mới đây, có thông tin cho rằng Huawei đang phát triển điện thoại gập Huawei Mate X3. Hôm nay, Digital Chat Station đã xác nhận một số thông số kỹ thuật chính của thiết bị. Có vẻ như ngày ra mắt Mate X3 có thể không còn xa nữa vì nó dường như đã nhận được sự chấp thuận từ cơ quan TENAA của Trung Quốc.",
  },
];
