import {
  productOne,
  productTwo,
  productThree,
  productFour,
  productFive,
  productSix,
  productSeven,
  productEight,
  productNine,
  productTen,
  productEleven,
  productTwelve,
  productThirdteen,
  productFourteen,
  productFifthteen,
  productSixteen,
} from "../../products/productData";
import Product from "../../products/Product";
export const slideProductData = [
  <Product {...productOne} />,
  <Product {...productTwo} />,
  <Product {...productThree} />,
  <Product {...productFour} />,
  <Product {...productFive} />,
  <Product {...productSix} />,
  <Product {...productSeven} />,
  <Product {...productEight} />,
  <Product {...productNine} />,
  <Product {...productTen} />,
  <Product {...productEleven} />,
  <Product {...productTwelve} />,
  <Product {...productThirdteen} />,
  <Product {...productFourteen} />,
  <Product {...productFifthteen} />,
  <Product {...productSixteen} />,
];
