//Comment Data
//Test git
//URL git new
export const productsData = [
  {
    id: 1,
    attribute: {
      name: "IPhone 12 ProMax 512GB",
      image: [
        "/images/products/product_1.jpg",
        "/images/products/product_2.jpg",
        "/images/products/product_3.jpg",
      ],
      price: "35.550.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 512,
      status: 10,
    },
    details: {
      description: "This is the best performance mobile phone in the world.",
      specifications: {
        screen:
          "OLED Resolution: 1284 x 2778 Pixels, 3 cameras 12 MP, 12 MP Wide screen: 6.7",
        OperatingSystem: "iOS 14",
        CPU: "Apple A14 Bionic 6 cores",
        ROM: "512GB",
        RAM: "6GB",
        NetworkSupport: "Phone",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3687mAh",
      },
    },
  },
  {
    id: 2,
    attribute: {
      name: "IPhone 12 ProMax 256GB",
      image: [
        "/images/products/product_2.jpg",
        "/images/products/product_1.jpg",
        "/images/products/product_3.jpg",
      ],
      price: "31.850.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.1' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        OperatingSystem: "iOS 14",
        CPU: "Apple A14 Bionic 6 cores",
        ROM: "256GB",
        RAM: "6GB",
        NetworkSupport: "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "189g",
        battery: "2815mAh",
      },
    },
  },
  {
    id: 3,
    attribute: {
      name: "IPhone 12 Mini 256GB",
      image: [
        "/images/products/product_3.jpg",
        "/images/products/product_2.jpg",
        "/images/products/product_1.jpg",
      ],
      price: "15.550.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 5.4' screen 60Hz.",
      specifications: {
        screen: "OLED 5.4' Super Retina XDR",
        OperatingSystem: "iOS 14",
        CPU: "Apple A14 Bionic",
        ROM: "256GB",
        RAM: "4GB",
        NetworkSupport: "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "135g",
        battery: "2227mAh",
      },
    },
  },
  {
    id: 4,
    attribute: {
      name: "Samsung Galaxy Z Fold 5G 2021",
      image: [
        "/images/products/product_4.jpg",
        "https://cdn.tgdd.vn/Products/Images/42/226099/samsung-galaxy-z-fold-2-den-600x600.jpg",
      ],
      price: "45.890.000",
      brand: "Samsung",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 7.59' and 6.73' screen 120Hz in the world.",
      specifications: {
        screen: "Chính: Dynamic AMOLED, Phụ: Super AMOLEDChính 7.59' & Phụ 6.23' Full HD+",
        OperatingSystem: "Android 11",
        CPU: "SnapDragron 865+",
        ROM: "256GB",
        RAM: "12GB",
        NetworkSupport: "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "282g",
        battery: "4500mAh",
      },
    },
  },
  {
    id: 5,
    attribute: {
      name: "Apple M1 - MacBook Air 13 512GB 2020",
      image: [
        "/images/products/product_5.jpg",
        "https://cdn.tgdd.vn/Products/Images/44/231250/macbook-air-m1-2020-gray-600x600.jpg",
      ],
      price: "30.590.000",
      brand: "Apple",
      type: "Laptop",
      color: ["gold", "gray"],
      memory: 512,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: " 13' Retina (2560 x 1600)",
        OperatingSystem: "MacOS",
        ROM: "512GB SSD",
        RAM: "16GB",
        graphics: "The 8-core GPU in M1 chip",
        chipset: "Apple M1",
        CPU: "Apple M1 chip with 8-core CPU, 8-core GPU, and 16-core Neural Engine",
        weight: "1.29kg",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 6,
    attribute: {
      name: "Apple M1 - MacBook Pro 13' 512GB 2020 ",
      image: [
        "/images/products/product_6.jpg",
        "https://cdn.tgdd.vn/Products/Images/44/236131/apple-macbook-pro-m1-2020-z11c000cj-600x600.jpg",
      ],
      price: "35.750.000",
      brand: "Apple",
      type: "Laptop",
      color: ["gray"],
      memory: 512,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Retina (2560 x 1600)",
        OperatingSystem: "MacOS",
        ROM: "512GB SSD",
        RAM: "16GB",
        graphics: "The 8-core GPU in M1 chip",
        chipset: "Apple M1",
        CPU: "Apple M1 chip with 8-core CPU, 8-core GPU, and 16-core Neural Engine",
        weight: "1.4kg",
        battery: "",
      },
    },
  },
  {
    id: 7,
    attribute: {
      name: "Laptop Dell XPS 13 9310 2 in 1 ",
      image: [
        "/images/products/product_7.jpg",
        "https://hanoicomputercdn.com/media/product/60448_laptop_dell_xps_13_9310_2_in_1_70260716_win10_bac_2.png",
      ],
      price: "41.680.000",
      brand: "Dell",
      type: "Laptop",
      color: ["white", "black", "gray"],
      memory: 1024,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        OperatingSystem: "Windows",
        ROM: "1TB HDD + 256GB SSD",
        RAM: "32GB",
        graphics: "NVIDIA GeForce GTX 1650Ti 4GB GDDR6 / Intel UHD Graphics",
        chipset: "Intel",
        CPU: "Intel Core i7-10750H ( 2.6 GHz - 5.0 GHz / 12MB / 6 nhân, 12 luồng )",
        weight: "2.2kg",
        battery: "",
      },
    },
  },
  {
    id: 8,
    attribute: {
      name: "Laptop MSI Katana Gaming GF66",
      image: [
        "/images/products/product_8.jpg",
        "https://cdn.tgdd.vn/Products/Images/44/242201/msi-gf66-11uc-i7-224vn-600x600.jpg",
      ],
      price: "37.990.000",
      brand: "MSI",
      type: "Laptop",
      color: ["black", "gray"],
      memory: 1024,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen:
          "15.6( 1920 x 1080 ) Full HD IPS 144Hz",
        OperatingSystem: "Windows 10 Home SL",
        ROM: "512GB SSD",
        RAM: "32GB",
        graphics: "NVIDIA GeForce GTX 3060 Max-Q 4GB GDDR6",
        chipset: "Intel",
        CPU: "i7 11800H 2.30 GHz",
        weight: "2.1kg",
        battery: "",
      },
    },
  },
  {
    id: 9,
    attribute: {
      name: "Apple Watch SE (4G) 44mm",
      image: [
        "/images/products/product_9.jpg",
        "https://hoanghamobile.com/i/preview/Uploads/2021/01/12/watch-se-lte-gold-loop.png",
      ],
      price: "9.190.000",
      brand: "Apple",
      type: "Watch",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "OLED 1.57 inch",
        OperatingSystem: "iOS",
        ROM: "32GB",
        RAM: "",
        NetworkSupport: "5G",
        SIM: "1 eSIM",
        weight: "39.7g",
        battery: "Khoảng 1.5 ngày",
      },
    },
  },
  {
    id: 10,
    attribute: {
      name: "Apple Watch Series 6 GPS + Cellular, 44mm Stainless Steel With Sport Band",
      image: [
        "/images/products/product_10.jpg",
        "https://hoanghamobile.com/i/preview/Uploads/2021/01/12/se-lte-silver.png",
        "https://hoanghamobile.com/i/preview/Uploads/2021/01/12/se-lte-gold.png",
      ],
      price: "17.750.000",
      brand: "Apple",
      type: "Watch",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "OLED 1.57 inch",
        OperatingSystem: "iOS",
        ROM: "32GB",
        RAM: "",
        NetworkSupport: "5G",
        SIM: "1 eSIM",
        weight: "39.7g",
        battery: "Khoảng 1.5 ngày",
      },
    },
  },
  {
    id: 11,
    attribute: {
      name: "Samsung Galaxy Watch 4 Classic 42mm LTE",
      image: [
        "/images/products/product_11.jpg",
        "https://hoanghamobile.com/i/preview/Uploads/2021/08/20/watch-4-classic-smail-7.png",
      ],
      price: "9.490.000",
      brand: "Samsung",
      type: "Watch",
      color: ["white", "black", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "SUPER AMOLED 1.19 inch",
        OperatingSystem: "Android",
        ROM: "16GB",
        RAM: "",
        NetworkSupport: "5G",
        SIM: "1 eSIM",
        weight: "40g",
        battery: "Khoảng 1.5 ngày",
      },
    },
  },
  {
    id: 12,
    attribute: {
      name: "Samsung Galaxy Watch 3 41mm",
      image: [
        "/images/products/product_12.jpg",
        "https://hoanghamobile.com/i/preview/Uploads/2021/06/25/r850-22333.png",
        "https://hoanghamobile.com/i/preview/Uploads/2021/06/25/image-removebg-preview.png",
      ],
      price: "5.250.000",
      brand: "Samsung",
      type: "Watch",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "SUPER AMOLED 1.19 inch",
        OperatingSystem: "Android",
        ROM: "16GB",
        RAM: "",
        NetworkSupport: "5G",
        SIM: "1 eSIM",
        weight: "40g",
        battery: "Khoảng 1.5 ngày",
      },
    },
  },
  {
    id: 13,
    attribute: {
      name: "Apple AirPods Pro",
      image: [
        "/images/products/product_13.jpg",
        "https://hoanghamobile.com/i/preview/Uploads/2020/10/27/image-removebg-preview%20(33).png",
      ],
      price: "4.990.000",
      brand: "Apple",
      type: "HeadPhone",
      color: ["white"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        OperatingSystem: "iOS",
        ROM: "256GB",
        RAM: "6GB",
        NetworkSupport: "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 14,
    attribute: {
      name: "Apple Beats Solo3 Wireless",
      image: [
        "/images/products/product_14.jpg",
        "https://hoanghamobile.com/i/preview/Uploads/2020/10/27/image-removebg-preview%20(37).png",
      ],
      price: "9.650.000",
      brand: "Apple",
      type: "HeadPhone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        OperatingSystem: "iOS",
        ROM: "256GB",
        RAM: "6GB",
        NetworkSupport: "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 15,
    attribute: {
      name: "Sony True Wireless WF-1000XM4",
      image: [
        "/images/products/product_15.jpg",
        "https://hoanghamobile.com/i/preview/Uploads/2021/06/10/image-removebg-preview-17.png",
      ],
      price: "6.990.000",
      brand: "Sony",
      type: "HeadPhone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        OperatingSystem: "Android",
        ROM: "256GB",
        RAM: "6GB",
        NetworkSupport: "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 16,
    attribute: {
      name: "Sony True Wireless WF-1000XM3",
      image: [
        "/images/products/product_16.jpg",
        "https://hoanghamobile.com/i/preview/Uploads/2020/11/07/tai-nghe-true-wireless-sony-wf-1000xm3.png",
      ],
      price: "3.650.000",
      brand: "Sony",
      type: "HeadPhone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        OperatingSystem: "Android",
        ROM: "256GB",
        RAM: "6GB",
        NetworkSupport: "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
];
