export const productsData = [
  {
    id: 1,
    attribute: {
      name: "IPhone 12 ProMax 512GB",
      image: "images/products/product_1.jpg",
      price: "35.550.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 512,
      status: 10,
    },
    details: {
      description: "This is the best performance mobile phone in the world.",
      specifications: {
        screen:
          "OLED Resolution: 1284 x 2778 Pixels, 3 cameras 12 MP, 12 MP Wide screen: 6.7",
        ROM: "512GB",
        RAM: "6GB",
        "Network Support": "Phone",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3687mAh",
      },
    },
  },
  {
    id: 2,
    attribute: {
      name: "IPhone 12 ProMax 256GB",
      image: "images/products/product_2.jpg",
      price: "31.850.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        ROM: "256GB",
        RAM: "6GB",
        "Network Support": "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 3,
    attribute: {
      name: "IPhone 12 Mini 256GB",
      image: "images/products/product_3.jpg",
      price: "27.750.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        ROM: "256GB",
        RAM: "6GB",
        "Network Support": "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 4,
    attribute: {
      name: "IPhone 12 Mini 256GB",
      image: "images/products/product_4.jpg",
      price: "27.750.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        ROM: "256GB",
        RAM: "6GB",
        "Network Support": "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 5,
    attribute: {
      name: "IPhone 12 Mini 256GB",
      image: "images/products/product_5.jpg",
      price: "27.750.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        ROM: "256GB",
        RAM: "6GB",
        "Network Support": "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 6,
    attribute: {
      name: "IPhone 12 Mini 256GB",
      image: "images/products/product_6.jpg",
      price: "27.750.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        ROM: "256GB",
        RAM: "6GB",
        "Network Support": "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 7,
    attribute: {
      name: "IPhone 12 Mini 256GB",
      image: "images/products/product_7.jpg",
      price: "27.750.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        ROM: "256GB",
        RAM: "6GB",
        "Network Support": "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 8,
    attribute: {
      name: "IPhone 12 Mini 256GB",
      image: "images/products/product_8.jpg",
      price: "27.750.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        ROM: "256GB",
        RAM: "6GB",
        "Network Support": "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 9,
    attribute: {
      name: "IPhone 12 Mini 256GB",
      image: "images/products/product_9.jpg",
      price: "27.750.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        ROM: "256GB",
        RAM: "6GB",
        "Network Support": "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 10,
    attribute: {
      name: "IPhone 12 Mini 256GB",
      image: "images/products/product_10.jpg",
      price: "27.750.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        ROM: "256GB",
        RAM: "6GB",
        "Network Support": "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 11,
    attribute: {
      name: "IPhone 12 Mini 256GB",
      image: "images/products/product_11.jpg",
      price: "27.750.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        ROM: "256GB",
        RAM: "6GB",
        "Network Support": "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 12,
    attribute: {
      name: "IPhone 12 Mini 256GB",
      image: "images/products/product_12.jpg",
      price: "27.750.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        ROM: "256GB",
        RAM: "6GB",
        "Network Support": "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 13,
    attribute: {
      name: "IPhone 12 Mini 256GB",
      image: "images/products/product_13.jpg",
      price: "27.750.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        ROM: "256GB",
        RAM: "6GB",
        "Network Support": "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 14,
    attribute: {
      name: "IPhone 12 Mini 256GB",
      image: "images/products/product_14.jpg",
      price: "27.750.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        ROM: "256GB",
        RAM: "6GB",
        "Network Support": "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 15,
    attribute: {
      name: "IPhone 12 Mini 256GB",
      image: "images/products/product_15.jpg",
      price: "27.750.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        ROM: "256GB",
        RAM: "6GB",
        "Network Support": "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
  {
    id: 16,
    attribute: {
      name: "IPhone 12 Mini 256GB",
      image: "images/products/product_16.jpg",
      price: "27.750.000",
      brand: "Apple",
      type: "Phone",
      color: ["white", "black", "red", "gray"],
      memory: 256,
      status: 6,
    },
    details: {
      description: "This is the 6.7' screen 60Hz in the world.",
      specifications: {
        screen: "Full HD 1280x720px",
        ROM: "256GB",
        RAM: "6GB",
        "Network Support": "5G",
        SIM: "1 Nano SIM & 1 eSIM",
        weight: "228g",
        battery: "3400mAh",
      },
    },
  },
];
